FROM node:18-alpine AS development

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

EXPOSE 3000
EXPOSE 9229

CMD ["pnpm", "run", "start:dev"]
